---
- name: test
  hosts: all
  gather_facts: no
  tasks:
  - name: showInterface
    ios_command:
      commands:
        - show ip int brief
    register: show_ip
  - debug: var=show_ip.stdout_lines
  - name: showRunInterface
    ios_command:
      commands:
        - show run int Ethernet0/0
    register: show_run
  - debug: var=show_run.stdout_lines
#cac lenh phai dung tren cisco
