---
- name: test
  hosts: all
  gather_facts: no
  tasks:
  - name: interfaceIPaddress
    ios_config:
      parents: interface Ethernet0/3
      lines:
        - des test
        - no ip address
        - ip address 218.100.10.10 255.255.255.0
        - no shutdown
        - duplex full
 
