---
- name: test
  hosts: all
  gather_facts: no
  tasks:
  - name: interfaceIPaddress
    ios_config:
      parents: interface Ethernet0/3
      lines:
        - des test
        - ip address 203.119.1.10 255.255.255.0
        - no shutdown
        - full-duplex
 
