---
- name: test
  hosts: all
  gather_facts: no
  tasks:
  - name: interfaceIPaddress
    ios_config:
      parents: interface Ethernet0/2
      lines:
        - des test
        - ip address 172.16.1.10 255.255.255.0
        - no shutdown
        - full-duplex
  - name: loopbackinterface
    ios_config:
      parents: interface loopback 0
      lines:
        - ip address 1.1.1.1 255.255.255.255
        - no shutdown
    
